### ISSUE TITLE
Improve probeye documentation

### ISSUE THREAD

**Issue by aklawonn** [BAMresearch/probeye#11]
Currently, there is only little documentation on how to use probeye. This must be improved. Both, the readme-file and the wiki must extended for this purpose.

**Comment by aklawonn** [comment]
We also should provide some examples. To that end, we could use the 8-school problem mentioned by Arpad in #18 and the bridge example described by Jan in #19.

**Comment by atulag0711** [comment]
We can use sphinx and create a make file. Maybe update the index, every time a new class is added.
