### ISSUE TITLE
type of sensors

### ISSUE THREAD

**Issue by joergfunger** [BAMresearch/probeye#12]
Currently, the base class of a sensor has no information, apart from the name. It might be advantageous to store information related to what is measured (e.g. displacements, temperature..). Even though this could be added to the name, it is easier to loop in the __call__ function of the forward model over the sensors and then decide based on the type what is returned.

**Comment by aklawonn** [comment]
That's a good idea, and also easy to implement. I could add a measurement_type and maybe also a unit-attribute to the sensor class. Would that be sufficient?

**Comment by joergfunger** [comment]
I would call this measurand

**Comment by aklawonn** [comment]
will do
