### ISSUE TITLE
Available priors

### ISSUE THREAD

**Issue by joergfunger** [BAMresearch/probeye#14]
From the definition directory, I was not able to find the definition which priors are implemented. This is somehow given in the emcee section, together with the implementation of the prior. IMO, the current implementation would mean to reimplement different priors when using different tools, even though from the definition point of view they are all the same (e.g. normal, Gamma). I would suggest to have a list of priors defined in the definition section (without the call function) and then derive emcee_normal, pyro_normal etc with the tool specific implementation (if this is needed at all). Another option could be to have specific call functions, e.g. call_scipy, call_pytorch, so that these priors can be evaluated using different libraries.

**Comment by TTitscher** [comment]
As far as I understand the idea, the user is free to define any distribution by some strings, e.g. 
~~~py
problem.add_parameter('a', ... prior=('normal', {'loc': loc_a, 'scale': scale_a}))
~~~
Then, in your "inference engine", you have something like [translate_prior_template](https://github.com/BAMresearch/probeye/blob/main/probeye/inference/emcee_/priors.py#L267) that converts this `"normal"` into an actual distribution.

**Comment by aklawonn** [comment]
Yes, I also understand it as Thomas just described it. For example, in Atul's Torch implementation, he would instantiate new prior-objects (based on Torch) which use the information provided in the definition-priors. But after this translation, the original prior-objects, that conveyed the prior-information, are not used anymore.

**Comment by joergfunger** [comment]
And even more important, what are the parameters, one might define a normal with mean and std_dev, the other one a normal with mean and var, if there is no standard way, than a problem defined for pyro cannot be used with emcee?

**Comment by aklawonn** [comment]
The parameters you define for your priors is up to you. You could call the parameters of your normal distribution potato and banana if you wanted to, you just have to remember this when writing your solver. If however (and this will be the standard case), you just want to use one of the existing solver-routines without writing them yourself, then of course your parameter names have to follow some convention. Currently, this convention for a normal and log-normal distribution is to call the mean 'loc' and the the standard distribution 'scale'. But this is not communicated anywhere yet, so yes, this is something that needs to be done. Also we need to keep make sure that this naming is consistent between different solvers.

**Comment by joergfunger** [comment]
Yes, the last point is important. And also for the reproducibility by describing this with an ontology of the calibration process, because otherwise you are not able to exactly define what was the prior that has been used (even independent of the solver used).

**Comment by TTitscher** [comment]
I suggest to use the distributions of `scipy.stats` for defining the prior. 
* they have _a lot_ of them and we do not have to implement them ourselves
*  `scipy` is likely already installed for everyone interested in the topic
* they are compatible with the paramnormal suggestion in #17
* Bonus point: they could be directly used by some solver engines like dynesty and emcee and the `translate_prior_template` would be trivial

**Comment by joergfunger** [comment]
The problem is that we can only add real numbers to generate a scipy distribution, but you cannot add a parameter that is identified, i.e. if your model prior is described by a normal distribution with a mean and std_dev, which themselves are hyperparameters to be identified (so you can't give a number).

**Comment by TTitscher** [comment]
Good old "prior priors", I see. Could we still use the functions and kwargs defined by scipy? Like 
`problem.set_prior("prm1", {"name": scipy.stats.crystalball, "loc"="prm1_loc", "scale"="prm2_scale"})`
