### ISSUE TITLE
Human friendly parametrization of distributions?

### ISSUE THREAD

**Issue by rozsasarpi** [BAMresearch/probeye#17]
It seems to be that quite some code is provided to define and use univariate distributions, e.g. https://github.com/BAMresearch/probeye/blob/1322317e9e9597b5ba5bf1871838cc98ded7458a/probeye/inference/emcee_/priors.py

If this is intended to be kept, then I would vote for a more standard and human friendly reparametrization of some `scipy` distributions as they are hard to remember and therefore error prone. The lognormal distribution is a great example, it could be parametrized with its mean and standard deviation. There is even a python package that does this for many `scipy` distributions: [`paramnormal`](https://github.com/phobson/paramnormal). What do you think?

**Comment by aklawonn** [comment]
The main reason for this seemingly cumbersome way of defining the priors is that no values (of constant prior-parameters) should be written to the prior-object. This allows to make prior-parameters latent if required. Apart from that we can also implement this in a different fashion. The approach with the getattr-method was implemented to allow the use of the different methods bundled in the scipy-object.

**Comment by aklawonn** [comment]
Ah, I see now. Yes, we can do that. This relates also to issue #14 where we agreed that the prior parameter should have meaningful and consistent names across the different solvers. By now I got used to this loc-scale convention, but we can certainly change that to mean and std for normal and lognormal distributions.
