### ISSUE TITLE
Implement possibility for vector-valued parameters

### ISSUE THREAD

**Issue by aklawonn** [BAMresearch/probeye#2]
Currently, all parameters are scalars. But there was some requests to also allow for vector valued parameters. To do so, one would probably have to add a new parameter-property 'length', and implement some additional changes.

**Comment by rozsasarpi** [comment]
I think this is a must have if you want to have a reasonable runtime for larger problems.

**Comment by joergfunger** [comment]
I think there is a misunderstanding. Vector valued parameters that Alex meant above relates to defining a parameter as a model parameter that is a vector (for a single model), e.g. if you want to identify a random field, those parameters of the random field (or the principal components). I think what @rozsasarpi means is the parallel evaluation of multiple forward models/likelihood in parallel, which could be implemented by passing a list of parameter dict and similarly returning a list of sensor outputs.
