### ISSUE TITLE
Coupling between parameters and priors

### ISSUE THREAD

**Issue by TTitscher** [BAMresearch/probeye#21]
We currently store information related to the prior in three places
1. `inference_problem.prior` (a dict with key `prm_name`)
2. `inference_problem.parameters["..."].prior `
3. `inference_problem.parameters["..."].role` (saying "latent" or "const")

This duplicate information makes it easy for the user to create inconsistent states and we need to restrict the access to the objects (#13) and need to implement methods like `change_parameter_role` and `change_constant` to keep everything in sync.

Suggestion:
* Assume: `inference_problem.prior` is the only place to store prior information and a parameter "x" is latent, `if "x" in inference_problem.priors`. 
* remove attributes `latent` and `prior` from the `ParameterProperties`

Then, it is much harder to create invalid states and we could simplify the related methods, e.g.
* `change_parameter_role` could become adding/removing its prior from `problem.priors`
* `change_constant` could become `problem.parameters["my_prm"].value = 42.`
* ...

**Comment by aklawonn** [comment]
I think it's a good idea to not store the priors at different independent locations, which then need to be kept in sync. But I would not separate the priors from the parameters by having a prior-list and a parameter-list, where the parameters don't have prior information anymore. I think the priors should be kept close to the parameters it refers to. I'm going to push proposal to address this issue soon.
