### ISSUE TITLE
Code formatting

### ISSUE THREAD

**Issue by TTitscher** [BAMresearch/probeye#25]
I'd appreciate if you could provide a way to reproduce the existing code formatting style of `probeye`, maybe in a `CONTRIBUTING.md` file (e.g. [here](https://tno-bim.gitlab.io/taralli/for_contributors.html#coding-conventions)). Otherwise, I expect the pull requests from collaborators (including me) to be either manually (=inconsistently) formatted or the diff to be cluttered with format changes.

[`black`](https://github.com/psf/black) is a common choice in python projects, but -- from my testing -- differs from the existing style (I assume pycharm). One way _could_ be to integrate [black into pycharm](https://youtrack.jetbrains.com/issue/PY-30757). Providing a way to reproduce the pycharm formatting with open source tools would also be fine.

**Comment by rozsasarpi** [comment]
I'm with @TTitscher :).

How about if we tried to write up @aklawonn's personal code formatting rules with one or more of the existing code checking and formatting packages? So things would be consistent and @aklawonn could still do the formatting manually and @TTitscher would have the option to do it automatically.

Maybe at this stage the formatting does not need to be enforced so it will not scare away contributors. (On the long run I'm in favor of having a bot automatically reformatting any non-compliant code and not allowing merging or pushing to the `main` if the formatting rules are not met.)
