### ISSUE TITLE
Make the sensor's error metric a method of the OutputSensor class

### ISSUE THREAD

**Issue by aklawonn** [BAMresearch/probeye#4]
Currently, the error metric (additive, multiplicative) is evaluated in the forward model's error function. It might be a good idea to move this functionality to the OutputSensor class.

**Comment by TTitscher** [comment]
Even if that may be practical, I think that calculating the error between a model and some data is not the job of a sensor (and maybe not that of a model). But I cannot come up with a better place...

**Comment by joergfunger** [comment]
We could also add that as a class/attribute to the noise model, e.g. we have a ZeroMeanGaussian noise model that is initialized with an error metric that gets as input the exp. data and the sensor and outputs the corresponding error. Or we implement directly different noise models, e.g. one for additive noise, and one for relative noise. Maybe the latter would be even better.

**Comment by aklawonn** [comment]
As discussed in our talks, the error methods have been moved to the noise model.
