### ISSUE TITLE
Workflow plan (json input --> main file --> output (csv,rdf,pickle..))

### ISSUE THREAD

**Issue by atulag0711** [BAMresearch/probeye#45]
Hi, 
Currently in the integration tests, we use commend line kind of workflow wherein we specify metadata needed by probeye lineby line. Going ahead we stick with the same or we have json input file which allows user to provide all the metadata (inference model,solver, metadata etc), called to a main file which provides required output and stores it as rdf/csv/pickle?

**Comment by rozsasarpi** [comment]
What would be the advantage of having a json input file?

**Comment by joergfunger** [comment]
I think we wanted to have the other way around, create the data structures witin probeye, and then export the triples within the module (probeye2RDF). The advantag is that all the functions that you call (e.g. the forward model) can directly be python functions (which at least from my point of view is tricky with the json input). In addition, you can directly use python functions (for example generating values or using processed values).
