### ISSUE TITLE
Restriction of the parameter range

### ISSUE THREAD

**Issue by SMattfeldt** [BAMresearch/probeye#69]
The issue should address the question of how to restrict the range of parameters that can be used by the various solvers.
In many cases, such as the diffusion problem, realistic parameter values are limited to a certain range of values. If the value range is not narrowed down, unrealistic results can occur.

A larger problem occurs when numerical iteration methods are needed to solve the forward model, such as the Newton method. With poor starting values, the problem occurred that the Newton method could not converge.

A solution idea would be to generate an “if-statement” in the “loglike” function that can be defined by the user. If the current parameter value is outside of the specified parameter range, "-inf" is returned. Otherwise, the same calculation of the “loglike” function is carried out as previously specified. An advantage of this integration would be that the execution of the forward model for the current parameter values would be omitted and thus runtime could be saved.

This could be implemented, for example, by defining boundaries for each parameter of the problem and accessing these boundaries in the “if-statement”.

**Comment by joergfunger** [comment]
In a similar line, but in a slightly different approach, a forward model would implement a check_parameters function that is called in the loglike function before the forward model itself (or by the user before the evaluation of the forward model). It would be great if you could make a branch and propose a pull request for the change. Maybe @aklawonn could point to the locations in the code that have to be changed.

**Comment by aklawonn** [comment]
Thanks for your feedback Sina, we all appreciate it! It's a good idea with the parameter ranges, and the good news is that it is already implemented to some extend in the export_to_rdf branch (see for example [here](https://github.com/BAMresearch/probeye/blob/export_to_rdf/probeye/definition/inference_problem.py), line 249). As you can see, each parameter is assigned a domain, which is equivalent to what you call range. However, no checks on this domain are implemented yet, so this is something you could do, if this is something you would like to do and if you have the time for it.

Here's what I would propose:

1. Create a branch from export_to_rdf
2. Implement a check_parameter_domains method of the class InferenceProblem in probeye/inference_problem.py, which for a given parameter vector theta checks if all given values are in the domains of each parameter. This method would return True or False depending on the check.
3. In probeye/inference/scipy/solver.py there is a method called loglike. This is the place where the parameters would be checked. The code line to add would look like `self.problem.check_parameter_domains(theta).` The check would happen before the for loop. If the check doesn't pass, the method would immediately return -np.inf.

**Comment by SMattfeldt** [comment]
The pull request is open: #70

**Comment by aklawonn** [comment]
The respective changes have been merged to the _export_to_rdf_ branch.
